
insert into categories (name)
values ('wedding'),
       ('disorganising'),
       ('party'),
       ('camping'),
       ('cooking'),
       ('outdoor'),
       ('birthday'),
       ('animal');

insert into users (name, password, last_online, registration_date)
values ('Armin', 'titok', '2024-08-07', '2023-11-10'),
       ('Laci', 'titok', '2022-04-12', '2020-03-19');

insert into events (date, time, location, creator_id, description, title)
values ('2024-01-01', '21:00:00', 'Budapest', 1, 'It is a long eed bys oppoontent hereblisor ''lorem ipsu eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncoverm'' will uncover many web sites still in their infancy. Various versions have evolved over the years, shumour andthe like).', 'Annas wedding party'),
       ('2026-12-12' , '15:30:00', 'London', 1, 'Lorem Ipsum id typeIt is a long eed bys oppoontent hereblisor ''lorem ipsu eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncoverm'' will uncover many web sites still in their infancy. Various versions have evolved over the years, shumour andthe like).It is a long eed bys oppoontent hereblisor ''lorem ipsu eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncoverm'' will uncover many web sites still in their infancy. Various versions have evolved over the years, shumour andthe like).It is a long eed bys oppoontent hereblisor ''lorem ipsu eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncoverm'' will uncover many web sites still in their infancy. Various versions have evolved over the years, shumour andthe like).setting scrambled it to make a type specimen book. It has survived not only fivearised in the 1960s with the release PageMaker including versions of Lorem Ipsum.', 'Annas divorce party'),
       ('2023-08-21' , '22:30:00', 'Berlin', 2,'Hey party people! Get ready to groove the night away at our epic disco event. Join us for an unforgettable night filled with funky beats, dazzling lights, and non-stop dancing. Grab your dancing shoes and get ready to boogie like never before. Don''t miss out on the ultimate disco experience!', 'disco rave party'),
       ('2025-12-11' , '18:15:00', 'Forest', 1,'Join us for a memorable weekend in the great outdoors! Escape the city hustle and enjoy thrilling adventures, delicious food, campfire storytelling, and so much more. Don''t miss out on this incredible camping experience. Book your spot now!', 'camping in the forest'),
       ('2023-11-12' , '16:00:00', 'Kitchen', 1,'Join us for a delicious culinary adventure! From mastering mouthwatering recipes to discovering new flavor combinations, our cooking event will leave your taste buds tingling. Don''t miss out on this fun-filled experience, where food and friends come together.', 'cooking together'),
       ('2024-01-03' , '12:00:00', 'Central Park', 1,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget varius justo, eget tempor nunc. Morbi blandit enim purus, a fermentum sapien rutrum a. Duis non nibh id neque cursus volutpat id vitae nisi. Sed vitae porta purus. Quisque a eros pretium, pharetra sapien non, lacinia est. Aenean volutpat sollicitudin metus vitae laoreet. Nam a volutpat lacus. Phasellus non enim in nisi fringilla lacinia. Ut vitae arcu ipsum. Ut sed convallis libero. Vestibulum elit enim, fringilla quis imperdiet id, molestie vitae tellus. ', 'Planting trees'),
       ('2024-06-14' , '17:00:00', 'Tokyo', 2,'Quisque in ullamcorper massa, non interdum augue. Integer hendrerit neque in leo rutrum, id efficitur magna efficitur. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur sollicitudin dui at augue bibendum, sit amet pretium dolor ultricies. Curabitur porttitor mauris turpis, eget elementum erat interdum in. Nulla mattis quis enim vel congue. Sed in risus consectetur, accumsan augue ac, faucibus libero.', 'Summer Festival'),
       ('2023-05-08' , '13:30:00', 'Ágfalva', 2,'Nam pulvinar turpis nec odio porta rutrum. Morbi vel mattis massa. Mauris sem nisi, tempor accumsan sapien sed, bibendum vehicula purus. Nam finibus nisl id sem efficitur tincidunt. Pellentesque condimentum auctor lacus id pellentesque. Suspendisse tincidunt turpis et lacus feugiat, ac vulputate lectus congue. Maecenas a ligula ante. Ut in elit nulla. Pellentesque commodo magna eu lorem feugiat sollicitudin. Cras rutrum vestibulum urna, eu egestas tortor convallis sit amet.       ', 'Grandmas birthday'),
       ('2023-03-17' , '10:00:00', 'Cat cafe', 1,'Sed iaculis velit vel metus volutpat, eu consectetur est egestas. Nullam a felis elementum, ultrices mi quis, fermentum velit. Nullam id sollicitudin arcu. Duis finibus blandit dui, ut malesuada lorem interdum sed. Duis ligula velit, semper vitae feugiat nec, consectetur eu lorem. Mauris sed erat cursus, rhoncus libero nec, viverra risus.', 'Cat cafe opening');

insert into events_categories (categories_id, events_id) values (1,1);
insert into events_categories (categories_id, events_id) values (2,2);
insert into events_categories (categories_id, events_id) values (3,3);
insert into events_categories (categories_id, events_id) values (4,4);
insert into events_categories (categories_id, events_id) values (5,5);
insert into events_categories (categories_id, events_id) values (6,6);
insert into events_categories (categories_id, events_id) values (3,7);
insert into events_categories (categories_id, events_id) values (7,8);
insert into events_categories (categories_id, events_id) values (8,9);

