
insert into categories (name)
values ('wedding'),
       ('disorganising');

insert into users (name, password, last_online, registration_date)
values ('Armin', 'titok', '2024-08-07', '2023-11-10'),
       ('Laci', 'titok', '2022-04-12', '2020-03-19');

insert into events (date_time, location, creator_id, description, title)
values ('2024-01-01', 'Budapest', 1, 'It is a long eed bys oppoontent hereblisor ''lorem ipsu eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncoverm'' will uncover many web sites still in their infancy. Various versions have evolved over the years, shumour andthe like).', 'Annas wedding party'),
       ('2026-34-87', 'London', 1, 'Lorem Ipsum id typeIt is a long eed bys oppoontent hereblisor ''lorem ipsu eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncoverm'' will uncover many web sites still in their infancy. Various versions have evolved over the years, shumour andthe like).It is a long eed bys oppoontent hereblisor ''lorem ipsu eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncoverm'' will uncover many web sites still in their infancy. Various versions have evolved over the years, shumour andthe like).It is a long eed bys oppoontent hereblisor ''lorem ipsu eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncover eed bys oppoontent hereblisor ''lorem ipsum'' will uncoverm'' will uncover many web sites still in their infancy. Various versions have evolved over the years, shumour andthe like).setting scrambled it to make a type specimen book. It has survived not only fivearised in the 1960s with the release PageMaker including versions of Lorem Ipsum.', 'Annas divorce party');

insert into events_categories (categories_id, events_id) values (1,1);
insert into events_categories (categories_id, events_id) values (2,2);

